services:
  # postgres container
  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./postgres_sql_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  # pgadmin container
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  # anaconda container to run ingestion script
  anaconda:
    image: continuumio/anaconda3
    volumes:
      - ./:/opt/notebooks
    ports:
      - "8888:8888"
    # install required python packages, jupyter, # create notebook server without creds/token
    command:
      /bin/bash -c "
      pip3 install --root-user-action=ignore -r /opt/notebooks/requirements.txt 
      && /opt/conda/bin/conda install jupyter -y --quiet
      && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0'
      --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' 
      "
    tty: true # “keep the container running”